# MODEL SETTINGS

training_dir: '../Netflix_Dataset/'
batch_size: 8
num_gpus: 1
num_nodes: 1
num_workers: 2
sample_size: 64
demo_every: 1000
demo_steps: 250
num_demos: 16
ema_decay: 0.995
seed: 42
accum_batches: 4
checkpoint_every: 10000
latent_dim: 0
cache_training_data: False
ckpt_path: ''
save_path: ''
start_method: 'spawn'
